CRAWLER:
  PRESS: [
    '경향신문',
    '국민일보',
    '동아일보',
    '문화일보',
    '서울신문',
    '세계일보',
    '조선일보',
    '중앙일보',
    '한겨레',
    '한국일보'
  ]
CLUSTER:
  SECTION: [
    '정치',
    '경제',
    '사회',
    '생활',
    'IT',
    '세계',
    '오피니언',
  ]
